import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:uuid/uuid.dart';

class ShazamApi {
  static const String _endpoint =
      'https://amp.shazam.com/discovery/v5/en/US/iphone/-/tag/';

  /// Performs a Shazam recognition request using the generated audio signature URI.
  /// [signatureUri] The base64 data URI generated by the Rust `generateSignature` function.
  static Future<Map<String, dynamic>?> recognizeSong(
    String signatureUri,
  ) async {
    final uuid = const Uuid().v4().toUpperCase();
    final url = Uri.parse('$_endpoint$uuid/$uuid');

    final payload = {
      'timezone': 'Europe/Paris',
      'signature': {'uri': signatureUri, 'samplems': 10000},
      'timestamp': DateTime.now().millisecondsSinceEpoch,
      'context': {},
      'geolocation': {},
    };

    try {
      final response = await http.post(
        url,
        headers: {
          'Content-Type': 'application/json',
          'User-Agent': 'Shazam/15.0.0 (iPhone; iOS 15.0; Scale/2.00)',
        },
        body: jsonEncode(payload),
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        return data;
      } else {
        throw Exception(
          'API returned status code ${response.statusCode}: ${response.body}',
        );
      }
    } catch (e) {
      throw Exception('Network request failed: $e');
    }
  }
}
